# .github/workflows/abc.yml
name: ABC Main Workflow

on:
  workflow_dispatch:
    inputs:
      messageForKLM:
        description: 'Message to send to KLM'
        required: false
        type: string
      messageForXYZ:
        description: 'Message to send to XYZ'
        required: false
        type: string

jobs:
  call-klm:
    uses: lourencek/gh-action-test/.github/workflows/klm.yml@main
    with:
      message: ${{ inputs.messageForKLM ||'klm blaa default' }}
      message2: ${{ inputs.messageForXYZ ||'klm dedae default' }}      

  call-xyz:
    uses: lourencek/gh-action-test/.github/workflows/xyz.yml@main
    with:
      message: ${{ inputs.messageForXYZ||'xyz default'}}
