name: Name of Town

on:
   workflow_call:
#  workflow_dispatch:
#    inputs:
#      townname:
#        description: 'Name of Town'
#        required: true
#        default: 'Auckland'

jobs:
  hello_user:
    runs-on: ubuntu-latest

    steps:
      - name: Name of Town user
        run: echo "You live in ${{ github.event.inputs.townname }}!"

      - name: Print Date and Time
        run: date
