# .github/workflows/klm.yml
name: sks Workflow

on:
  workflow_dispatch:
    inputs:
      message:
        required: false
        type: string
      message2:
        required: false
        type: string        

jobs:
  print-message:
    runs-on: ubuntu-latest
    steps:
      - run: echo "KLM received message:${{ inputs.message || 'World sks' }}"
      - run: echo "KLM received message:${{ inputs.message2 || 'World2 sks' }}"      
      
