# .github/workflows/xyz.yml
name: XYZ Workflow

on:
  workflow_call:
    inputs:
      message:
        required: true
        type: string

jobs:
  print-message:
    runs-on: ubuntu-latest
    steps:
      - run: echo "XYZ received message:${{ inputs.message }}"
